service: marketproApi
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 2048
  stage: dev
  timeout: 15


functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{ptoxy+}
      - http: ANY /
    environment:
      MONGO_URI: mongodb+srv://admin001:admin001@cluster0.qrhnp.mongodb.net/couponcode?retryWrites=true&w=majority
      TWILIO_ACCOUNT_SID: AC1d07d30069913c667e0d01533f720d13
      TWILIO_AUTH_TOKEN: 3a229e30c74b22b2d69e63675526a80a

	
plugins:
  - serverless-plugin-include-dependencies
